-- ═══════════════════════════════════════════════════════════════
--  002: Users Table
-- ═══════════════════════════════════════════════════════════════
--  3NF compliance:
--    • Every non-key column depends on the PK (id) and nothing else.
--    • No transitive dependencies — role is an ENUM, not a FK to a
--      roles table, because we only have 3 fixed roles (YAGNI).
--
--  Security:
--    • password_hash stores bcrypt output (~60 chars), NEVER plaintext.
--    • last_login_ip supports both IPv4 and IPv6 via INET type.
--    • email uses CITEXT-like behavior via a UNIQUE index on LOWER(email)
--      so "John@Email.com" and "john@email.com" are treated as duplicates.
-- ═══════════════════════════════════════════════════════════════

-- Custom ENUM types for type safety at the database level.
-- PostgreSQL ENUMs are stored as 4 bytes internally (same as INT),
-- but provide CHECK-like validation without a separate constraint.
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('admin', 'user', 'auditor');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
  -- UUID v4 primary key — generated by PostgreSQL, not the app.
  -- DEFAULT gen_random_uuid() means INSERTs don't need to supply an id.
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- ── Identity ───────────────────────────────────────────────
  email           VARCHAR(255) NOT NULL,
  password_hash   VARCHAR(255) NOT NULL,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  phone           VARCHAR(20),

  -- ── Authorization ──────────────────────────────────────────
  -- Default 'user' — admins are promoted manually or via seed.
  role            user_role NOT NULL DEFAULT 'user',

  -- ── Status ─────────────────────────────────────────────────
  is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,

  -- ── Audit fields ───────────────────────────────────────────
  -- INET type natively handles IPv4 ("192.168.1.1") and
  -- IPv6 ("::1") with validation — VARCHAR would allow garbage.
  last_login_at   TIMESTAMPTZ,
  last_login_ip   INET,

  -- ── Timestamps ─────────────────────────────────────────────
  -- TIMESTAMPTZ stores in UTC internally, converts on display
  -- based on the session's timezone setting.
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Case-insensitive unique email ────────────────────────────
-- UNIQUE constraint on LOWER(email) so "A@B.com" = "a@b.com".
-- This is superior to a simple UNIQUE on email because it
-- prevents duplicate accounts with different casing.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
  ON users (LOWER(email));

-- ── Auto-update updated_at on every UPDATE ───────────────────
-- This trigger fires BEFORE UPDATE and sets updated_at = NOW().
-- Without this, every UPDATE query would need to manually include
-- SET updated_at = NOW(), which is error-prone.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop and recreate to make migration idempotent
DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
