-- ═══════════════════════════════════════════════════════════════
--  003: Accounts Table
-- ═══════════════════════════════════════════════════════════════
--  Represents bank accounts owned by users.
--
--  3NF compliance:
--    • user_id is a FK to users — no user data duplicated here.
--    • account_number is independently unique (business key).
--    • currency is stored per-account to support multi-currency.
--
--  Financial precision:
--    • NUMERIC(15,2) stores up to 9,999,999,999,999.99
--    • NUMERIC is arbitrary-precision (unlike FLOAT/DOUBLE which
--      suffer from IEEE 754 rounding: 0.1 + 0.2 ≠ 0.3).
--    • CHECK(balance >= 0) prevents negative balances at the DB level
--      as a safety net — business logic also validates this.
--
--  Concurrency:
--    • balance updates use SELECT ... FOR UPDATE (row-level locking)
--      in stored procedures to prevent race conditions.
-- ═══════════════════════════════════════════════════════════════

DO $$ BEGIN
  CREATE TYPE account_type AS ENUM ('savings', 'checking', 'business');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE account_status AS ENUM ('active', 'frozen', 'closed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS accounts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- ── Owner ──────────────────────────────────────────────────
  -- ON DELETE CASCADE: if a user is deleted, their accounts go too.
  -- In production, you'd typically soft-delete users instead.
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- ── Account Identity ───────────────────────────────────────
  -- 12-digit numeric string, generated by the application.
  -- VARCHAR(20) instead of BIGINT to preserve leading zeros and
  -- support non-numeric prefixes in the future.
  account_number  VARCHAR(20) NOT NULL UNIQUE,

  -- ── Account Properties ─────────────────────────────────────
  account_type    account_type NOT NULL DEFAULT 'savings',
  balance         NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  currency        VARCHAR(3) NOT NULL DEFAULT 'INR',
  status          account_status NOT NULL DEFAULT 'active',

  -- ── Timestamps ─────────────────────────────────────────────
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- ── Constraints ────────────────────────────────────────────
  -- Defense-in-depth: even if application logic has a bug,
  -- the database will reject negative balances.
  CONSTRAINT chk_balance_non_negative CHECK (balance >= 0)
);

-- ── Indexes ──────────────────────────────────────────────────
-- user_id is queried on every login (fetch user's accounts),
-- so a B-tree index is essential.
CREATE INDEX IF NOT EXISTS idx_accounts_user_id
  ON accounts(user_id);

-- ── Auto-update trigger (reuses the function from 002) ───────
DROP TRIGGER IF EXISTS set_accounts_updated_at ON accounts;
CREATE TRIGGER set_accounts_updated_at
  BEFORE UPDATE ON accounts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
