-- ═══════════════════════════════════════════════════════════════
--  009: Fraud Explanations Tables
-- ═══════════════════════════════════════════════════════════════
--  Stores natural-language explanations generated by the LLM
--  for transactions flagged by the deterministic fraud engine.
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS fraud_explanations (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id    UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  explanation       TEXT NOT NULL,
  retrieved_context JSONB NOT NULL DEFAULT '{}',
  model_used        VARCHAR(255) NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- A transaction can only have one base explanation
  CONSTRAINT uq_fraud_explanations_transaction UNIQUE (transaction_id)
);

CREATE TABLE IF NOT EXISTS fraud_explanation_turns (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id    UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  question          TEXT NOT NULL,
  answer            TEXT NOT NULL,
  retrieved_context JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_fraud_explanation_turns_txn
  ON fraud_explanation_turns(transaction_id, created_at ASC);
